import type { Config } from "tailwindcss";

// Stitch 디자인 토큰을 그대로 포팅 (색상/폰트/사이즈/여백/라운드)
const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container": "#eaedff",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#351000",
        "tertiary-fixed-dim": "#ffb695",
        "surface-container-low": "#f2f3ff",
        "on-secondary-fixed-variant": "#005236",
        secondary: "#006c49",
        "secondary-container": "#6cf8bb",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#a44100",
        "tertiary-fixed": "#ffdbcc",
        "outline-variant": "#c7c4d8",
        "secondary-fixed": "#6ffbbe",
        "inverse-surface": "#283044",
        "on-surface": "#131b2e",
        tertiary: "#7e3000",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#464555",
        "on-tertiary-container": "#ffd2be",
        "surface-container-highest": "#dae2fd",
        "on-background": "#131b2e",
        "surface-bright": "#faf8ff",
        "surface-variant": "#dae2fd",
        "on-secondary-fixed": "#002113",
        primary: "#3525cd",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#7b2f00",
        "on-error": "#ffffff",
        "on-primary-container": "#dad7ff",
        surface: "#faf8ff",
        "primary-fixed": "#e2dfff",
        outline: "#777587",
        "inverse-primary": "#c3c0ff",
        background: "#faf8ff",
        error: "#ba1a1a",
        "surface-dim": "#d2d9f4",
        "on-secondary-container": "#00714d",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#4edea3",
        "surface-tint": "#4d44e3",
        "inverse-on-surface": "#eef0ff",
        "on-primary-fixed-variant": "#3323cc",
        "surface-container-high": "#e2e7ff",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#0f0069",
        "primary-fixed-dim": "#c3c0ff",
        "primary-container": "#4f46e5",
      },
      spacing: {
        "space-md": "1rem",
        margin: "1.25rem",
        "gutter-mobile": "0.75rem",
        "space-sm": "0.5rem",
        gutter: "1rem",
        "space-lg": "1.5rem",
        "space-xs": "0.25rem",
        "margin-mobile": "1rem",
        "space-xl": "2rem",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "Pretendard", "Noto Sans KR", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "Pretendard", "Noto Sans KR", "sans-serif"],
        "display-currency": ["Plus Jakarta Sans", "Pretendard", "Noto Sans KR", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "Pretendard", "Noto Sans KR", "sans-serif"],
        "body-lg-bold": ["Plus Jakarta Sans", "Pretendard", "Noto Sans KR", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "Pretendard", "Noto Sans KR", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "Pretendard", "Noto Sans KR", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "Pretendard", "Noto Sans KR", "sans-serif"],
        "display-currency-mobile": ["Plus Jakarta Sans", "Pretendard", "Noto Sans KR", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "Pretendard", "Noto Sans KR", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "Pretendard", "Noto Sans KR", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "display-currency": ["38px", { lineHeight: "46px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg-bold": ["18px", { lineHeight: "28px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "headline-md": ["22px", { lineHeight: "30px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "display-currency-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "body-md": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-sm": ["19px", { lineHeight: "26px", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
export default config;
